### ISSUE TITLE
Load Font error in app

### ISSUE THREAD

**Issue by Aloynz** [jianminglok/FitHup#4]
Does not seem to affect the font displayed but error message is still present.

"fontFamily "RobotoMedium" is not a system font and has not been loaded through Font.loadAsync.
- If you intended to use a system font, make sure you typed the name correctly and that it is supported by your device operating system.
- If this is a custom font, be sure to load it with Font.loadAsync."

**Comment by jianminglok** [comment]
#5 Issue should be fixed upon merging this commit
